package storage

import (
	"context"
	"time"
)

// EventListQuery describes one paged Events table query.
type EventListQuery struct {
	TenantID   string    // TenantID is the tenant boundary key
	ProjectID  string    // ProjectID is the project or website boundary key
	SourceID   string    // SourceID is the source boundary key inside the project
	EventName  string    // EventName optionally filters to one analytics event name
	DistinctID string    // DistinctID optionally filters to one visitor or user key
	From       time.Time // From optionally filters events at or after this event time
	To         time.Time // To optionally filters events before this event time
	Limit      int       // Limit caps returned rows before the builder-level maximum
	Offset     int       // Offset skips rows for Events pagination
}

// RealtimeQuery describes the recent-events query used by Realtime.
type RealtimeQuery struct {
	TenantID  string    // TenantID is the tenant boundary key
	ProjectID string    // ProjectID is the project or website boundary key
	SourceID  string    // SourceID is the source boundary key inside the project
	Since     time.Time // Since filters events at or after this event time
	Limit     int       // Limit caps returned rows before the builder-level maximum
}

// EventQueryPlan is the SQL and argument plan generated by a storage adapter.
type EventQueryPlan struct {
	SQL           string // SQL is the generated query with driver placeholders
	Args          []any  // Args are the bound query values in driver order
	LogicalTable  string // LogicalTable is the stable model name exposed to analysis modules
	PhysicalTable string // PhysicalTable is the adapter-owned ClickHouse table name
	Limit         int    // Limit is the effective row cap after defaults and maximums
}

// EventRecord is one event row returned by an analytics query.
type EventRecord struct {
	ID             string    // ID is the stable event id used for idempotent ingestion
	TenantID       string    // TenantID is the tenant boundary key
	ProjectID      string    // ProjectID is the project or website boundary key
	SourceID       string    // SourceID is the source boundary key inside the project
	SourceType     string    // SourceType is the source category such as web, server, or mobile
	EventName      string    // EventName is the analytics event name
	DistinctID     string    // DistinctID is the visitor or user identity key
	SessionID      string    // SessionID is the optional session key
	EventTime      time.Time // EventTime is the timestamp produced by the source
	ReceivedAt     time.Time // ReceivedAt is the timestamp accepted by collect
	Properties     string    // Properties is the serialized event-scoped JSON payload
	UserProperties string    // UserProperties is the serialized user-scoped JSON payload
	Source         string    // Source is the optional source label for diagnostics
}

// EventQueryBuilder builds storage-specific event query plans.
type EventQueryBuilder interface {
	// BuildEventsQuery builds the paged Events table query.
	BuildEventsQuery(context.Context, EventListQuery) (EventQueryPlan, error)
	// BuildRealtimeQuery builds the recent-events Realtime query.
	BuildRealtimeQuery(context.Context, RealtimeQuery) (EventQueryPlan, error)
}

// EventReader executes event queries against the storage backend.
type EventReader interface {
	// ListEvents returns paged Events rows for one tenant/project/source.
	ListEvents(context.Context, EventListQuery) ([]EventRecord, error)
	// ListRealtime returns recent Realtime rows for one tenant/project/source.
	ListRealtime(context.Context, RealtimeQuery) ([]EventRecord, error)
}
