package storage

import (
	"context"
	"time"
)

// EventListQuery describes one paged Events table query.
type EventListQuery struct {
	TenantID   string    // TenantID is the tenant boundary key
	ProjectID  string    // ProjectID is the project or website boundary key
	SourceID   string    // SourceID is the source boundary key inside the project
	EventName  string    // EventName optionally filters to one analytics event name
	DistinctID string    // DistinctID optionally filters to one visitor or user key
	From       time.Time // From optionally filters events at or after this event time
	To         time.Time // To optionally filters events before this event time
	Limit      int       // Limit caps returned rows before the builder-level maximum
	Offset     int       // Offset skips rows for Events pagination
}

// RealtimeQuery describes the recent-events query used by Realtime.
type RealtimeQuery struct {
	TenantID  string    // TenantID is the tenant boundary key
	ProjectID string    // ProjectID is the project or website boundary key
	SourceID  string    // SourceID is the source boundary key inside the project
	Since     time.Time // Since filters events at or after this event time
	Limit     int       // Limit caps returned rows before the builder-level maximum
}

// EventQueryPlan is the SQL and argument plan generated by a storage adapter.
type EventQueryPlan struct {
	SQL           string // SQL is the generated query with driver placeholders
	Args          []any  // Args are the bound query values in driver order
	LogicalTable  string // LogicalTable is the stable model name exposed to analysis modules
	PhysicalTable string // PhysicalTable is the adapter-owned ClickHouse table name
	Limit         int    // Limit is the effective row cap after defaults and maximums
}

// EventQueryBuilder builds storage-specific event query plans.
type EventQueryBuilder interface {
	// BuildEventsQuery builds the paged Events table query.
	BuildEventsQuery(context.Context, EventListQuery) (EventQueryPlan, error)
	// BuildRealtimeQuery builds the recent-events Realtime query.
	BuildRealtimeQuery(context.Context, RealtimeQuery) (EventQueryPlan, error)
}
